### ISSUE TITLE
help

### ISSUE THREAD

**Issue by KKDDD** [mbelmadani/moead-py#5]
Why i can't install exceptions module by using pip.
And do you have some two-dimension or higher muti-objective optimization problem example

**Comment by mbelmadani** [comment]
Was the module required to run the example code? What version of python and which command line are you using? Let me know if that's still an issue, I don't remember needing to install an exceptions module, otherwise I will close for now.

Note that this was developed for python 2, most likely python2.7 (can't remember exactly.)
